# Generated by Django 4.1 on 2022-09-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Budget_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="countslist",
            name="card_number",
        ),
        migrations.AddField(
            model_name="countslist",
            name="card_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
